services:
  rag-backend:
    build: .
    container_name: rag_api_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/1
      - PORT=8000
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./storage:/app/storage
    depends_on:
      - redis
    restart: unless-stopped
  
  redis:
    image: redis:7-alpine
    container_name: rag_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery-worker:
    build: .
    container_name: rag_celery_worker
    command: celery -A tasks.celery_app worker --loglevel=info --concurrency=2
    env_file:
      - .env
    environment: 
      - REDIS_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./storage:/app/storage
    depends_on:
      - redis
    restart: unless-stopped